export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_USER_FILE = 'SET_USER_FILE';
export const CLEAR_SEARCH_PARAMS = 'CLEAR_SEARCH_PARAMS';

export const GET_CANDIDATES_DATA_START =  'GET_CANDIDATES_DATA_START';
export const GET_CANDIDATES_DATA_SUCCESS =  'GET_CANDIDATES_DATA_SUCCESS';
export const GET_CANDIDATES_DATA_FAILED = 'GET_CANDIDATES_DATA_FAILED';

export const SET_PROFILE_SCORE_START = 'SET_PROFILE_SCORE_START';
export const SET_PROFILE_SCORE_SUCCESS = 'SET_PROFILE_SCORE_SUCCESS';
export const SET_PROFILE_SCORE_FAILED = 'SET_PROFILE_SCORE_FAILED';

export const UPDATE_CANDIDATE_START = 'UPDATE_CANDIDATE_START';
export const UPDATE_CANDIDATE_SUCCESS = 'UPDATE_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_FAILED = 'UPDATE_CANDIDATE_FAILED';

export const DELETE_CANDIDATE_START = 'DELETE_CANDIDATE_START';
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_FAILED = 'DELETE_CANDIDATE_FAILED';

export const CLEAR_RECRUIT = 'CLEAR_RECRUIT';
