export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_ROLE = 'SET_USER_ROLE';
export const SET_USER_FILE = 'SET_USER_FILE';
export const CLEAR_SEARCH_PARAMS = 'CLEAR_SEARCH_PARAMS';

export const SET_PROFILE_SCORE_SUCCESS = 'GET_PROFILE_SCORE_SUCCESS';
export const SET_PROFILE_SCORE_FAILED = 'GET_PROFILE_SCORE_FAILED';
